version: '2'
services:
#  using pipeline/influx
  # nxos-pipeline:
  #   build: nxos-pipeline
  #   ports:
  #     - 57500:57500
  #   volumes:
  #     - ./nxos-pipeline/config:/etc/pipeline
  #   links:
  #     - "elasticsearch:elasticsearch"
  #     - "prometheus:prometheus"
  #   depends_on:
  #     - iosxr-pipeline
  #     - elasticsearch
  #     - prometheus
  #     - influxdb

  unified-pipeline:
    build: unified-pipeline
    ports:
      - 57500:57500
      # - 5432:5432
    volumes:
      - ./unified-pipeline/config:/etc/pipeline
    links:
      - "elasticsearch:elasticsearch"
      - "prometheus:prometheus"
    depends_on:
      # - iosxr-pipeline
      - elasticsearch
      - prometheus
      - influxdb
    environment:
      - influx_ip=influxdb
      - influx_port=8086

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"


  # iosxr-pipeline:
  #   build: iosxr-pipeline
  #   ports:
  #     - 5432:5432
  #   command: "./startup.sh"
  #   links:
  #     - "influxdb:influxdb"
  #     - "prometheus:promethus"
  #   volumes:
  #     - ./iosxr-pipeline/config:/etc/pipeline
  #   depends_on:
  #     - influxdb
  #     - prometheus
  #     - unified-pipeline
  #   environment:
  #     - influx_ip=influxdb
  #     - influx_port=8086



  influxdb:
    image: influxdb:1.1.3
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
    ports:
      - "8086:8086"
      - "8083:8083"

  prometheus:
    image: prom/prometheus:v1.5.2
    volumes:
      - ./prometheus:/etc/prometheus
    command: "-config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:master
    volumes:
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/datasources:/etc/grafana/datasources
    ports:
      - "3000:3000"
    environment:
     - "GF_LOG_LEVEL=debug"
     - "GF_LOG_FILTERS=alerting.notifier.webhook:debug"
     - "GF_AUTH_ANONYMOUS_ENABLED=true"
     - "GF_DASHBOARDS_JSON_ENABLED=true"
     - "GF_DASHBOARDS_JSON_PATH=/etc/grafana/dashboards/"
     - "GF_PATHS_DATASOURCES=/etc/grafana/datasources/"
     - "GF_PATHS_PROVISIONING=/etc/grafana/"
    links:
      - "influxdb:influxdb"
      - "prometheus:prometheus"
    depends_on:
      - influxdb
      - prometheus
