stages:
  - validate
  - deploy_to_prod
  - deploy_to_test
  - verify_deploy_to_prod
  - verify_deploy_to_test
  - verify_website_reachability

lint:
  stage: validate
  image: kecorbin/ansible:devel
  variables:
  script:
    - ansible-playbook --syntax-check -i inventory/prod.yaml site.yaml
    - ansible-playbook --syntax-check -i inventory/test.yaml site.yaml

deploy_to_prod:
  image: kecorbin/ansible:devel
  stage: deploy_to_prod
  script:
    - echo "Deploy to prod env"
    - ansible-playbook -i inventory/prod.yaml site.yaml
  environment:
    name: production
  only:
  - production

deploy_to_test:
  image: kecorbin/ansible:devel
  stage: deploy_to_test
  script:
    - echo "Deploy to test env"
    - ansible-playbook -i inventory/test.yaml site.yaml
  environment:
    name: test
  only:
  - test

verify_prod_environment:
  image: ciscotestautomation/pyats:latest-robot
  stage: verify_deploy_to_prod
  environment:
    name: test
  script:
    - pwd
    - cd tests
    # important: need to add our current directory to PYTHONPATH
    - export PYTHONPATH=$PYTHONPATH:$(pwd)
    - robot prod.robot

  artifacts:
      name: "PROD_${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
      when: always
      paths:
        - ./tests/log.html
        - ./tests/report.html
        - ./tests/output.xml
  only:
  - production

verify_test_environment:
  image: ciscotestautomation/pyats:latest-robot
  stage: verify_deploy_to_test
  environment:
    name: test
  script:
    - pwd
    - cd tests
    # important: need to add our current directory to PYTHONPATH
    - export PYTHONPATH=$PYTHONPATH:$(pwd)
    - robot test.robot
  only:
  - test

  artifacts:
      name: "TEST_${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
      when: always
      paths:
        - ./tests/log.html
        - ./tests/report.html
        - ./tests/output.xml
  only:
  - test


internet_sites:
  image: ciscotestautomation/pyats:latest-robot
  stage: verify_website_reachability
  environment:
    name: test
  script:
    - pwd
    - cd tests/websites/
    - make test
  only:
  - production
