site_name: NetDevOps Sandbox Labs
site_description: a description
repo_name: GitHub
repo_url: https://github.com/DevNetSandbox/sbx_multi_ios
docs_dir: docs/

theme:
  name: 'material'

nav:
  - Overview: index.md
  - Sandbox Setup: sandbox-setup.md
  - Labs:
    - NSO with Ansible: labs/nso-with-ansible.md
    - NSO with Ansible (Part 2): labs/nso-service-development.md
    - Visualizing Telemetry Data with Grafana: labs/metrics-grafana.md
    # WIP: additioonal labs need blogged @julio
    # - Telemetry with PIG: labs/telemetry-with-pig.md
    # - Using PYATS with Jenkins: labs/using_pyats_with_jenkins.md
    # - cicd-xxxxx
    # - etc.


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tasklist
  - codehilite

plugins:
  - search
