{
 "title": "WAN Overview",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_Producer]]",
     "groupBy": [
      { "params": [ "Producer" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization",
     "query": "SELECT \"total-cpu-one-minute\" FROM \"autogen\".\"Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization\" WHERE $timeFilter GROUP BY \"Producer\"",
     "select": [
      [
       { "params": [ "total-cpu-fifteen-minute" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_Producer]]",
     "groupBy": [
      { "params": [ "Producer" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary",
     "query": "SELECT 100 - ((\"free-physical-memory\" / \"system-ram-memory\") * 100) FROM \"autogen\".\"Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary\" WHERE $timeFilter GROUP BY \"Producer\"",
     "select": [
      [
       { "params": [ "system-ram-memory" ], "type": "field" },
       { "params": [ "-" ], "type": "math" }
      ],
      [
       { "params": [ "free-physical-memory" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "OSPF Neighbor Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_Producer]]",
     "groupBy": [
      { "params": [ "Producer" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ipv4-ospf-oper:ospf/processes/process/default-vrf/ospf-summary",
     "select": [
      [
       { "params": [ "sa-num-nbrs-up" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "OSPF Routes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_Producer",
     "groupBy": [
      { "params": [ "Producer" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rib-ipv4-oper:rib/rib-table-ids/rib-table-id/summary-protos/summary-proto",
     "select": [
      [
       {
        "params": [
         "proto-route-count__active-routes-count"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "ospf" }
     ]
    }
   ]
  },
  {
   "title": "BGP Prefixes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "total",
     "measurement": "Cisco-IOS-XR-ipv4-bgp-oper:bgp/instances/instance/instance-active/default-vrf/process-info",
     "select": [
      [
       { "params": [ "vrf__path-count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "vrf-name", "operator": "=", "value": "default" }
     ]
    }
   ]
  },
  {
   "title": "BGP Adjacencies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_Producer",
     "groupBy": [
      { "params": [ "Producer" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ipv4-bgp-oper:bgp/instances/instance/instance-active/default-vrf/process-info",
     "select": [
      [
       { "params": [ "vrf__neighbors-count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance-name", "operator": "=", "value": "default" }
     ]
    }
   ]
  },
  {
   "title": "Traffic Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_Producer - [[tag_interface-name]]",
     "groupBy": [
      { "params": [ "Producer" ], "type": "tag" },
      { "params": [ "interface-name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
     "query": "SELECT non_negative_derivative(last(\"bytes-received\"), 1s) *8 FROM \"Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters\" WHERE $timeFilter GROUP BY time($interval), \"interface-name\" fill(null)",
     "select": [
      [
       { "params": [ "bytes-sent" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}