
all:
  vars:
    nso:
      ip: localhost
      url: http://localhost:8080/jsonrpc
      username: admin
      password: admin

  children:
    access:
      hosts:

        access1:
          nso_device_name: access1
          oob_mgmt_ip: 172.16.30.225

    core:
      hosts:

        core2:
          nso_device_name: core2
          oob_mgmt_ip: 172.16.30.222

        core1:
          nso_device_name: core1
          oob_mgmt_ip: 172.16.30.221

    distribution:
      hosts:

        dist1:
          nso_device_name: dist1
          oob_mgmt_ip: 172.16.30.223
          peer_mgmt_ip: 172.16.30.224

        dist2:
          nso_device_name: dist2
          oob_mgmt_ip: 172.16.30.224
          peer_mgmt_ip: 172.16.30.223
