version: '2'
services:
  unified-pipeline:
    build: unified-pipeline
    ports:
      - 57500:57500
      # - 5432:5432
    volumes:
      - ./unified-pipeline/config:/etc/pipeline
    links:
      - "influxdb:influxdb"
    depends_on:
      - influxdb
    environment:
      - influx_ip=influxdb
      - influx_port=8086




  influxdb:
    image: influxdb:1.1.3
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
    ports:
      - "8086:8086"
      - "8083:8083"


  grafana:
    image: grafana/grafana:master
    # volumes:
    #   - ./grafana/dashboards:/etc/grafana/dashboards
    #   - ./grafana/datasources:/etc/grafana/datasources
    ports:
      - "3000:3000"
    environment:
     - "GF_LOG_LEVEL=debug"
     - "GF_LOG_FILTERS=alerting.notifier.webhook:debug"
     - "GF_AUTH_ANONYMOUS_ENABLED=true"
     - "GF_DASHBOARDS_JSON_ENABLED=true"
     - "GF_DASHBOARDS_JSON_PATH=/etc/grafana/dashboards/"
     - "GF_PATHS_DATASOURCES=/etc/grafana/datasources/"
     - "GF_PATHS_PROVISIONING=/etc/grafana/"
    links:
      - "influxdb:influxdb"
    depends_on:
      - influxdb
