version: '2'
services:

  telegraf:
    # Full tag list: https://hub.docker.com/r/library/telegraf/tags/
    image: telegraf:1.4.4
    environment:
      HOSTNAME: "telegraf-getting-started"
    # Telegraf requires network access to InfluxDB
    links:
      - influxdb
    volumes:
      # Mount for telegraf configuration
      - ./telegraf/:/etc/telegraf/
      - ./mibs:/root/.snmp/mibs
      # Mount for Docker API access
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb

  web:
    build: web
    ports:
      - 5001:5000
    environment:
      - "NSO_URL=http://10.10.20.50:8080"
      - "NSO_USERNAME=admin"
      - "NSO_PASSWORD=admin"

  influxdb:
    # Full tag list: https://hub.docker.com/r/library/influxdb/tags/
    image: influxdb:1.3.7
    volumes:
      # Mount for influxdb data directory
      # - ./influxdb/data:/var/lib/influxdb
      # Mount for influxdb configuration
      - ./influxdb/config/:/etc/influxdb/
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"

  grafana:
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/datasources:/etc/grafana/datasources
    environment:
       - "GF_DASHBOARDS_JSON_ENABLED=true"
       - "GF_DASHBOARDS_JSON_PATH=/etc/grafana/dashboards/"
       - "GF_PATHS_DATASOURCES=/etc/grafana/datasources/"
       - "GF_PATHS_PROVISIONING=/etc/grafana/"
    links:
      - influxdb:influxdb
    depends_on:
      - influxdb
