
---

- name: Creating Device Groups
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Create Device Group
      nso_config:
        url: "http://localhost:8080/jsonrpc"
        username: "admin"
        password: "admin"
        data:
          tailf-ncs:devices:
            device-group:
              - name: all-devices
                device-name:
                  - nx
                  - xe
                  - xr

from genie.conf import Genie
from genie.ops.utils import get_ops
tb = Genie.init(testbed)
